### ISSUE TITLE
How to calculate the grid_num and grid_size in common.py?

### ISSUE THREAD

**Issue by Picrew** [lamda-bbo/WireMask-BBO#1]
Hello,I want fix with ibm datasets，i find every datasets have own grid_num and grid_size，eg.grid_setting = {"adaptec1": {"grid_num": 160, "grid_size": 72}, "adaptec2": {"grid_num": 158, "grid_size": 96}...} Can ur tell me how to calculate the parameter?

**Comment by Picrew** [comment]
fix it

**Comment by xiaosiCU** [comment]
"grid_num" or "grid_size" are actually hyper-parameters that to be determined by the users. For a defalut setting, grid_num=224 could perform well under most circumstances. Then "grid_size" could be calculated directly according to the die size.
